---

- hosts: all
  become: true
  tasks:

  - name: Install Packages
    apt:
      name: 
        - apache2
        - tmux
        - libapache2-mod-php
        - neovim
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
