---

- hosts: all
  become: true
  tasks:

  - name: Install Packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ tmux_package }}"
        - "{{ vim_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
