---

- hosts: all
  become: true
  tasks:

  - name: Install Packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ tmux_package }}"
        - "{{ vim_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Stop Apache Service 
    tags: stop
    service:
      name: apache2
      state: stopped
      enabled: no

# Could not get command unarchive to work
# - hosts: workstation
#   become: true
#   tasks:
# 
#     - name: Install Unzip
#       package: 
#         name: unzip
# 
#     - name: Install Terraform
#       command: curl -o /usr/local/bin/terraform.zip https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_arm64.zip
