-j-

- hosts: all
  become: true
  tasks:

  - name: Remove Packages
    apt:
      name: 
        - apache2
        - tmux
        - libapache2-mod-php
        - neovim
      state: absent 
    when: ansible_distribution == "Ubuntu"
