---

- hosts: all
  become: true
  tasks:

  - name: Remove Packages
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ tmux_package }}"
        - "{{ vim_package }}"
      state: absent 
    when: ansible_distribution == "Ubuntu"
