---

- hosts: all
  become: true
  pre_tasks:
    - name: Install Update
      tags: always
      package:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: server1
  become: true
  tasks:
  - name: Server 1 -> Install Packages
    tags: ubuntu,apache,apache2,php,tmux,vim,server1
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ tmux_package }}"
        - "{{ vim_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: server2
  become: true
  tasks:
  - name: Server 2 -> Install Packages
    tags: ubuntu,apache,apache2,php,tmux,vim,server2
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
        - "{{ tmux_package }}"
        - "{{ vim_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
